openapi: 3.0.0
info:
  title: Luniverse API
  version: 1.0.2
servers: 
  - url: https://luniverse.io/v1/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Account Management
    description: 계정 관리 관련 API
  - name: Ben Test API
    description: Integration API Test
paths:
  /{protocol}/{network}/accounts/{address}/balance:
    $ref: './test1.yaml#/paths/~1{protocol}~1{network}~1accounts~1{address}~1balance'
  tags: 
    - Account Management
  /{protocol}/{network}/accounts/{address}/helloworld:
    $ref: './test2.yaml#/paths/~1{protocol}~1{network}~1accounts~1{address}~1helloworld'
  tags: 
    - Ben Test API