openapi: 3.0.0
info:
  title: Luniverse API
  version: 1.0.2
servers: 
  - url: https://luniverse.io/v2/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  $ref: './API_Reference/index.yaml'

