openapi: 3.0.0
info:
  title: Luniverse API
  version: 1.0.2
servers: 
  - url: https://luniverse.io/v2/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /{protocol}/{network}/accounts/{address}/balance:
    get:
      $ref: './Nova_NFT_API/test1.yaml#/paths/~1{protocol}~1{network}~1accounts~1{address}~1balance/get'
  /{protocol}/{network}/accounts/{address}/helloworld/myworld :
    post:
      $ref: './Nova_Account_API/test2.yaml#/path~/~1{protocol}~1{network}~1accounts~1{address}~1helloworld~1myworld/post'