openapi: 3.0.0
info:
  title: Luniverse API
  version: 1.0.2
servers: 
    - url: https://luniverse.io/v1/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Account Management
    description: 계정 관리 관련 API
paths:
  /{protocol}/{network}/accounts/{address}/balance:
    get:
      security: 
        - bearerAuth : []
      # tags:
      #   - Account Management
      summary: "특정 주소의 계정 잔액 조회"
      operationId: test1
      parameters:
        - name: protocol
          in: path
          required: true
          schema:
            type: string
            default : ethereum
          description: 실행할 블록체인의 프로토콜을 선택합니다.  이를 위해 ~합니다.
        - name: network
          in: path
          required: true
          schema:
            type: string
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 성공적인 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: array
                    items:
                      type: object
                      properties:
                        assetType:
                          type: string
                        balance:
                          type: string
